scdb_host: localhost:8080
port: 8080
protocol: http
query_result_callback_timeout: 3m
session_expire_time: 3m
session_expire_check_time: 1m
log_level: debug
storage:
  type: sqlite
  conn_str: "/root/autodl-tmp/scql/examples/scdb-tutorial/scdb/scdb_hive.db"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  spu: |
    {
        "protocol": "SEMI2K",
        "field": "FM64"
    }
party_auth:
  method: none
  enable_timestamp_check: false
  validity_period: 1m

